### ISSUE TITLE
'https' parameter isn't available

### ISSUE THREAD

**Issue by deep8317** [EEParker/aspnetcore-vueclimiddleware#73] opened 2020-10-13 03:22 UTC
As mentioned in the documentation, I am using endpoint routing for development. Also, I installed an SSL certificate using `mkcert`. Now, I am getting an error **Failed to proxy the request to http://localhost:8080/**

The reason is: Vue.js app is now running at **https://localhost:8080**

I have tried to include `https: true` within `endpoints.MapToVueCliProxy(
                        "{*path}",
                        new SpaOptions { SourcePath = "ClientApp" },
                        npmScript: "serve",
                        regex: "Compiled successfully",
                        forceKill: true);` but **https** parameters doesn't exist in `MapToVueCliProxy` extension method.

I am using **VueCliMiddleware** V 3.1.1 via NuGet package.

Please advice further to resolve this issue. 

Thanks.

**Comment by bryandam** [comment] 2020-10-13 15:04
The problem is that @EEParker hasn't released a new NPM package with that code as tracked by issue #53.

**Comment by deep8317** [comment] 2020-10-14 03:37
@bryandam Thanks for your response.

I have referenced the library manually to make things work and test the project locally.

@EEParker Are you planning to update the NuGet package anytime soon? Thank you!

**Comment by TobbenTM** [comment] 2020-10-14 08:28
@deep8317 

As an alternative, I made a PR to make this experience better here: https://github.com/EEParker/aspnetcore-vueclimiddleware/pull/74

If you want to use this before it gets merged and released, you can simply update your Vue CLI to a recent version, and add the following environment variable:

![image](https://user-images.githubusercontent.com/1180644/95963418-f69d5c80-0e07-11eb-8010-3eaf83329280.png)

**Comment by EEParker** [comment] 2020-10-15 20:46
This should be live on nuget as version 3.1.2, thanks.

**Closed by EEParker** 2020-10-15 20:46 UTC
