### ISSUE TITLE
SocketException: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by J4S0Nc** [EEParker/aspnetcore-vueclimiddleware#37] opened 2019-12-20 21:53 UTC
I've wired up a aspnet core 3.1 app and Vue 2.6 following the samples here. I am able to get updates in the browser when I make changes to my vue components most of the time. But sometimes (seems random) I will lose connection to the web socket. My VS debugger is still attached and I can still hit my API endpoints, but anything through the proxy fails with `SocketException: No connection could be made because the target machine actively refused it. `

If I restart my debugger it starts to work again, but then will randomly drop off at some point. 

my endpoints in the startup file:

```
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();

#if DEBUG
                if (System.Diagnostics.Debugger.IsAttached)
                    endpoints.MapToVueCliProxy("{*path}", new SpaOptions { SourcePath = "ClientApp" }, "serve", regex: "running at");//"Compiled successfully"
                else
#endif
                    // note: output of vue cli should be wwwroot
                    endpoints.MapFallbackToFile("index.html");


            });
```

Any ideas?

**Comment by rothariger** [comment] 2019-12-21 00:28
i have the same issue, but if you check your running processes you will find that you have several node process running.

i guess it's not fault from the helper, as the same is happening with react developments that i have, and i'm migrating them to core 3.1, so i suppose that there is something wrong with core 3.x.

**Comment by J4S0Nc** [comment] 2019-12-23 20:29
I don't appear to have the same issue as #33, but maybe I read it wrong. My issue is with the debugger continuously running (never stopping it). I have noticed a pattern to when it might break. It seems when I save changes to the JS in a vue component file, instead of the page updating it just drops the connection (I'm guessing the process dies, but not sure how to check). I can change HTML and don't see the same issue, but changing JS and saving appears to trigger it more often than not.

**Comment by rothariger** [comment] 2019-12-23 21:00
in the output window, search for the last port generated. something like this:
![image](https://user-images.githubusercontent.com/7863660/71380445-f51b5300-25ad-11ea-9a45-caccd8eeb7f5.png)

and check which port is it, if you have 8081, or something like that, you have the same issue as #33...

**Comment by EEParker** [comment] 2019-12-24 04:36
If the port mismatch is your issue, it is typically caused by orphaned nodejs processes.

**Comment by restofever** [comment] 2019-12-30 17:32
The pull request #32 should kill those orphaned node processes.

**Comment by EEParker** [comment] 2020-01-09 21:48
I have merged the PR and updated the samples.

**Closed by EEParker** 2020-01-09 21:48 UTC
